# render.yaml - MusicMatch Deployment

services:
  - type: web
    name: MusicMatch
    env: python
    region: oregon
    plan: free
    repo: https://github.com/bilal2004RS/MusicMatch
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    autoDeploy: true
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        value: your_secret_key_here
